// export const pokemonList = [
//     { name: "Bulbasaur", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png" },
//     { name: "Ivysaur", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png" },
//     { name: "Venusaur", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png" },
//     { name: "Charmander", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png" },
//     { name: "Charmeleon", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png" },
//     { name: "Charizard", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png" },
//     { name: "Squirtle", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png" },
//     { name: "Wartortle", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png" },
//     { name: "Blastoise", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png" },
//     { name: "Caterpie", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png" },
//     { name: "Metapod", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png" },
//     { name: "Butterfree", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png" },
//     { name: "Weedle", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png" },
//     { name: "Kakuna", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png" },
//     { name: "Beedrill", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png" },
//     { name: "Pidgey", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png" },
//     { name: "Pidgeotto", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png" },
//     { name: "Pidgeot", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png" },
//     { name: "Rattata", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png" },
//     { name: "Raticate", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png" },
//     { name: "Spearow", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png" },
//     { name: "Fearow", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png" },
//     { name: "Ekans", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png" },
//     { name: "Arbok", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png" },
//     { name: "Pikachu", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png" },
//     { name: "Raichu", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png" },
//     { name: "Sandshrew", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png" },
//     { name: "Sandslash", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png" },
//     { name: "Nidoran♀", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png" },
//     { name: "Nidorina", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png" },
//     { name: "Nidoqueen", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png" },
//     { name: "Nidoran♂", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png" },
//     { name: "Nidorino", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png" },
//     { name: "Nidoking", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png" },
//     { name: "Clefairy", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png" },
//     { name: "Clefable", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png" },
//     { name: "Vulpix", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/037.png" },
//     { name: "Ninetales", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/038.png" },
//     { name: "Jigglypuff", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png" },
//     { name: "Wigglytuff", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/040.png" },
//     { name: "Zubat", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/041.png" },
//     { name: "Golbat", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/042.png" },
//     { name: "Oddish", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/043.png" },
//     { name: "Gloom", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/044.png" },
//     { name: "Vileplume", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/045.png" },
//     { name: "Paras", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/046.png" },
//     { name: "Parasect", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/047.png" },
//     { name: "Venonat", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/048.png" },
//     { name: "Venomoth", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png" },
//     { name: "Diglett", imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/050.png" }
//   ];
  

export const pokemonList = [
  { name: "Bulbasaur", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png" },
  { name: "Ivysaur", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png" },
  { name: "Venusaur", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png" },
  { name: "Charmander", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png" },
  { name: "Charmeleon", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png" },
  { name: "Charizard", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png" },
  { name: "Squirtle", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png" },
  { name: "Wartortle", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png" },
  { name: "Blastoise", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png" },
  { name: "Caterpie", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png" },
  { name: "Metapod", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png" },
  { name: "Butterfree", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png" },
  { name: "Weedle", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png" },
  { name: "Kakuna", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png" },
  { name: "Beedrill", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png" },
  { name: "Pidgey", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png" },
  { name: "Pidgeotto", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png" },
  { name: "Pidgeot", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png" },
  { name: "Rattata", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png" },
  { name: "Raticate", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png" },
  { name: "Spearow", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png" },
  { name: "Fearow", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png" },
  { name: "Ekans", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png" },
  { name: "Arbok", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png" },
  { name: "Pikachu", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png" },
  { name: "Raichu", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png" },
  { name: "Sandshrew", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png" },
  { name: "Sandslash", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png" },
  { name: "Nidoran♀", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png" },
  { name: "Nidorina", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png" },
  { name: "Nidoqueen", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png" },
  { name: "Nidoran♂", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png" },
  { name: "Nidorino", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png" },
  { name: "Nidoking", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png" },
  { name: "Clefairy", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png" },
  { name: "Clefable", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png" },
  { name: "Vulpix", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/037.png" },
  { name: "Ninetales", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/038.png" },
  { name: "Jigglypuff", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png" },
  { name: "Wigglytuff", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/040.png" },
  { name: "Zubat", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/041.png" },
  { name: "Golbat", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/042.png" },
  { name: "Oddish", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/043.png" },
  { name: "Gloom", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/044.png" },
  { name: "Vileplume", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/045.png" },
  { name: "Paras", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/046.png" },
  { name: "Parasect", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/047.png" },
  { name: "Venonat", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/048.png" },
  { name: "Venomoth", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png" },
  { name: "Diglett", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/050.png" },
  { name: "Dugtrio", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/051.png" },
  { name: "Meowth", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/052.png" },
  { name: "Persian", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/053.png" },
  { name: "Psyduck", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png" },
  { name: "Golduck", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/055.png" },
  { name: "Mankey", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/056.png" },
  { name: "Primeape", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/057.png" },
  { name: "Growlithe", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/058.png" },
  { name: "Arcanine", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/059.png" },
  { name: "Poliwag", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/060.png" },
  { name: "Poliwhirl", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/061.png" },
  { name: "Poliwrath", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/062.png" },
  { name: "Abra", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png" },
  { name: "Kadabra", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/064.png" },
  { name: "Alakazam", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/065.png" },
  { name: "Machop", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/066.png" },
  { name: "Machoke", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/067.png" },
  { name: "Machamp", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/068.png" },
  { name: "Bellsprout", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/069.png" },
  { name: "Weepinbell", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/070.png" },
  { name: "Victreebel", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/071.png" },
  { name: "Tentacool", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/072.png" },
  { name: "Tentacruel", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/073.png" },
  { name: "Geodude", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/074.png" },
  { name: "Graveler", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/075.png" },
  { name: "Golem", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/076.png" },
  { name: "Ponyta", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/077.png" },
  { name: "Rapidash", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/078.png" },
  { name: "Slowpoke", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/079.png" },
  { name: "Slowbro", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/080.png" },
  { name: "Magnemite", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/081.png" },
  { name: "Magneton", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/082.png" },
  { name: "Farfetch'd", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/083.png" },
  { name: "Doduo", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/084.png" },
  { name: "Dodrio", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/085.png" },
  { name: "Seel", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/086.png" },
  { name: "Dewgong", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/087.png" },
  { name: "Grimer", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/088.png" },
  { name: "Muk", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/089.png" },
  { name: "Shellder", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/090.png" },
  { name: "Cloyster", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/091.png" },
  { name: "Gastly", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/092.png" },
  { name: "Haunter", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/093.png" },
  { name: "Gengar", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/094.png" },
  { name: "Onix", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/095.png" },
  { name: "Drowzee", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/096.png" },
  { name: "Hypno", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/097.png" },
  { name: "Krabby", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/098.png" },
  { name: "Kingler", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/099.png" },
  { name: "Voltorb", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/100.png" },
  { name: "Electrode", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/101.png" },
  { name: "Exeggcute", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/102.png" },
  { name: "Exeggutor", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/103.png" },
  { name: "Cubone", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/104.png" },
  { name: "Marowak", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/105.png" },
  { name: "Hitmonlee", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/106.png" },
  { name: "Hitmonchan", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/107.png" },
  { name: "Lickitung", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/108.png" },
  { name: "Koffing", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/109.png" },
  { name: "Weezing", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/110.png" },
  { name: "Rhyhorn", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/111.png" },
  { name: "Rhydon", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/112.png" },
  { name: "Chansey", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/113.png" },
  { name: "Tangela", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/114.png" },
  { name: "Kangaskhan", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/115.png" },
  { name: "Horsea", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/116.png" },
  { name: "Seadra", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/117.png" },
  { name: "Goldeen", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/118.png" },
  { name: "Seaking", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/119.png" },
  { name: "Staryu", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/120.png" },
  { name: "Starmie", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/121.png" },
  { name: "Mr. Mime", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/122.png" },
  { name: "Scyther", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/123.png" },
  { name: "Jynx", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/124.png" },
  { name: "Electabuzz", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/125.png" },
  { name: "Magmar", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/126.png" },
  { name: "Pinsir", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/127.png" },
  { name: "Tauros", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/128.png" },
  { name: "Magikarp", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/129.png" },
  { name: "Gyarados", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/130.png" },
  { name: "Lapras", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/131.png" },
  { name: "Ditto", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/132.png" },
  { name: "Eevee", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/133.png" },
  { name: "Vaporeon", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/134.png" },
  { name: "Jolteon", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/135.png" },
  { name: "Flareon", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/136.png" },
  { name: "Porygon", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/137.png" },
  { name: "Omanyte", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/138.png" },
  { name: "Omastar", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/139.png" },
  { name: "Kabuto", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/140.png" },
  { name: "Kabutops", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/141.png" },
  { name: "Aerodactyl", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/142.png" },
  { name: "Snorlax", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/143.png" },
  { name: "Articuno", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/144.png" },
  { name: "Zapdos", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/145.png" },
  { name: "Moltres", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/146.png" },
  { name: "Dratini", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/147.png" },
  { name: "Dragonair", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/148.png" },
  { name: "Dragonite", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png" },
  { name: "Mewtwo", url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png" }
];
